# Generated by Django 3.2.5 on 2021-07-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystem', '0002_auto_20210726_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamName',
            new_name='Societie',
        ),
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='SocietyCandidate',
        ),
    ]
