# Generated by Django 3.2.5 on 2021-07-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystem', '0006_remove_societycandidate_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='candidate', to='votingsystem.societycandidate')),
            ],
        ),
    ]
